#!/usr/bin/env node
// One-shot extractor — parses the Python prototype files and emits TS modules.
// Idempotent: safe to re-run if Python source changes.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const PROTOTYPES = [
  {
    pyPath: "./scripts/prototypes/pet_preview3.py",
    arrayName: "cat",
    paletteName: "cat_palette",
    paletteSymbols: { "_": 0, "O": 1, "C": 2, "L": 3, "E": 4, "P": 5, "N": 6, "W": 7, "Y": 8 },
    outPath: "src/pets/cat/sprite-data.ts",
  },
  {
    pyPath: "./scripts/prototypes/pet_preview5.py",
    arrayName: "capybara",
    paletteName: "cp",
    paletteSymbols: { "_": 0, "Oc": 1, "Cb": 2, "Lb": 3, "Fb": 4, "Bl": 5, "Sb": 6, "Nb": 7 },
    outPath: "src/pets/capybara/sprite-data.ts",
  },
];

function parsePythonArray(src, varName, symbols) {
  // Sort symbols by length descending so longer names ("Oc") match before shorter ("O")
  const sortedKeys = Object.keys(symbols).sort((a, b) => b.length - a.length);

  const re = new RegExp(`^${varName}\\s*=\\s*\\[`, "m");
  const startMatch = src.match(re);
  if (!startMatch) throw new Error(`Cannot find ${varName} in source`);
  const startIdx = startMatch.index + startMatch[0].length;

  // Walk forward matching brackets to find the end of the outer array
  let depth = 1;
  let i = startIdx;
  while (i < src.length && depth > 0) {
    const ch = src[i];
    if (ch === "[") depth++;
    else if (ch === "]") depth--;
    i++;
  }
  if (depth !== 0) throw new Error(`Unterminated array for ${varName}`);
  const body = src.slice(startIdx, i - 1);

  const rows = [];
  for (const line of body.split("\n")) {
    const rowMatch = line.match(/\[([^\]]+)\]/);
    if (!rowMatch) continue;
    const tokens = rowMatch[1].split(",").map((t) => t.trim()).filter(Boolean);
    const ints = tokens.map((t) => {
      // Try longest symbol first to handle multi-char tokens (Oc before O)
      for (const k of sortedKeys) {
        if (t === k) return symbols[k];
      }
      const n = Number(t);
      if (Number.isFinite(n)) return n;
      throw new Error(`Unknown token: '${t}' in ${varName}`);
    });
    rows.push(ints);
  }
  if (rows.length === 0) throw new Error(`No rows parsed for ${varName}`);
  return rows;
}

function parsePalette(src, varName) {
  const re = new RegExp(`^${varName}\\s*=\\s*\\{`, "m");
  const startMatch = src.match(re);
  if (!startMatch) throw new Error(`Cannot find palette ${varName}`);
  const startIdx = startMatch.index + startMatch[0].length;

  let depth = 1;
  let i = startIdx;
  while (i < src.length && depth > 0) {
    const ch = src[i];
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    i++;
  }
  const body = src.slice(startIdx, i - 1);

  const palette = {};
  for (const line of body.split("\n")) {
    const m = line.match(/(\d+)\s*:\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/);
    if (m) palette[Number(m[1])] = [Number(m[2]), Number(m[3]), Number(m[4])];
  }
  return palette;
}

function emitTs(rows, palette) {
  return [
    `// AUTO-GENERATED by scripts/extract-sprites.mjs — do not edit by hand.`,
    `import type { Palette } from "../types.js";`,
    ``,
    `export const palette: Palette = ${JSON.stringify(palette, null, 2)};`,
    ``,
    `export const idle: number[][] = ${JSON.stringify(rows)};`,
    ``,
  ].join("\n");
}

for (const p of PROTOTYPES) {
  const src = readFileSync(p.pyPath, "utf8");
  const rows = parsePythonArray(src, p.arrayName, p.paletteSymbols);
  const palette = parsePalette(src, p.paletteName);
  mkdirSync(dirname(p.outPath), { recursive: true });
  writeFileSync(p.outPath, emitTs(rows, palette));
  console.log(`✓ ${p.outPath} (${rows.length} rows × ${rows[0].length} cols)`);
}
